package org.catinthedark.alyoep.game

object States {
    val SPLASH_SCREEN = "SPLASH_SCREEN"
    val PLAYER_SCREEN = "PLAYER_SCREEN"
    val TITLE_SCREEN = "TITLE_SCREEN"
    val GAME_OVER_SCREEN = "GAME_OVER_SCREEN"
    val WIN_SCREEN = "WIN_SCREEN_STATE"
    val TEST_AUDIO_SCREEN = "TEST_AUDIO_SCREEN_STATE"
    val ENEMIES_SCREEN = "ENEMIES_SCREEN"
}
